### ISSUE TITLE
add ADOC (pdf+html) artifacts to isaqb-org.github.io

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-adoc#11]
ADOC artifacts need to be downloadable.

We need:
* a travis-ci build to create artifacts and a github-page
* to include ADOC into the index.html of isaqb-org.github.io

**Comment by programming-wolf** [comment]
travis-ci is replaced by GitHub Actions. They are already active in branch [v2020-draft](https://github.com/isaqb-org/curriculum-adoc/tree/v2020-draft)

**Comment by programming-wolf** [comment]
Done.
