### ISSUE TITLE
LGs in "schön" umformulieren

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-adoc#14]
Die waren vorher in drei Teile (können, verstehen, kennen) untergliedert. Das lieber in einzelne Lernziele runterbrechen:

Beispiel:
==== LZ 1-1: Nutzen und Ziele von Architekturdokumentation verstehen

* Architekturdokumentation ist kein Selbstzweck
* Den Nutzen und die verschiedenen Ziele von Architekturdokumentation beschreiben, beispielsweise: 
   ** Architekturdokumentation unterstützt beim Lösungsentwurf, und bei der Kommunikation der Lösung dem Team und anderen (z. B. Auftraggebern) gegenüber.
   ** Unterstützung der Entwicklung durch Vermittlung architektur- und entwicklungsrelevanter Entscheidungen, Fakten und Gründe.
   ** Schriftliche Kommunikation relevanter struktureller und konzeptioneller Sachverhalte
   ** Konservierung von Wissen über Entwicklung und Architektur
* Diese Ziele und den Nutzen gegenüber Stakeholdern überzeugend vertreten können.

(unter /resources sind die Original-Lehrpläne im repo)

**Comment by programming-wolf** [comment]
Ist abgeschlossen.
