### ISSUE TITLE
Add steps to clone and build in the Readme

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-adoc#15]
I think it would be helpful to add the steps to build in the readme file.
Something like

```
$ git clone https://github.com/isaqb-org/curriculum-adoc.git --recursive
$ cd curriculum-adoc
$ ./gradlew
```

The error message without --recursive is really strange. 
Other option add: Add a link to the generell template for usage.

**Comment by programming-wolf** [comment]
Done.
