### ISSUE TITLE
create LG for chapter 1

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-adoc#2]
mal ein erster Versuch, die kennen/verstehen Absätze in Lernziele zu transformieren:

[[LZ-1-1]]
==== LZ 1-1: Nutzen und Ziele von Architekturdokumentation verstehen

* Architekturdokumentation ist kein Selbstzweck
* Den Nutzen und die verschiedenen Ziele von Architekturdokumentation beschreiben, beispielsweise: 
   ** Architekturdokumentation unterstützt beim Lösungsentwurf, und bei der Kommunikation der Lösung dem Team und anderen (z. B. Auftraggebern) gegenüber.
   ** Unterstützung der Entwicklung durch Vermittlung architektur- und entwicklungsrelevanter Entscheidungen, Fakten und Gründe.
   ** Schriftliche Kommunikation relevanter struktureller und konzeptioneller Sachverhalte
   ** Konservierung von Wissen über Entwicklung und Architektur
* Diese Ziele und den Nutzen gegenüber Stakeholdern überzeugend vertreten können.

==== LZ 1-2: Bedeutung von Architekturdokumentation für unterschiedliche Stakeholder verstehen

* Verstehen, dass unterschiedliche Stakeholder i.d.R. verschiedene Anforderungen an Architekturdokumentation haben, beispielsweise hinsichtlich:
** Arten von Informationen (etwa: über Schnittstellen, Bausteine, querschnittliche Themen, Entscheidungen, technische Risiken, Lösungsansätze oä)
** Darstellung solcher Informationen (als (grafische) Modelle, als reine Grafiken oder textuell)
** Detaillierungsgrad (etwa: Überblick, abstrakte oder detaillierte Darstellung)
** technische Repräsentation (mit/ohne Schreib-/Änderungsmöglichkeiten, PDF, HTML, Wiki, Textverarbeitung oä)
** Grad der Aktualität

==== LG 1-3: Architekturdokumentation gegen andere Arten von Dokumentation abgrenzen

* Verstehen, dass Architekturdokumentation Berührungspunkte und teilweise Überdeckung zu anderen Arten vo Dokumentation besitzt, beispielsweise:
** Anforderungs-/Requirements-Dokumentation
** Implementierungsdokumentation
** Managementdokumentation
** Testdokumentation
** Betriebsdokumentation

==== LG 1-4: Typische Notations- und Darstellungsmittel für Architekturdokumentation kennen

* Verschiedene Notations- und Darstellungsmittel für Architekturinformationen kennen, beispielsweise:
** Modellierungsmethoden, beispielsweise UML, BPMN, ER-Diagramme, Ereignis-Prozessketten (ePK)
** Textuelle Erläuterungen von Entscheidungen

* UML ist für Architekturdokumentation hilfreich, aber nicht zwingend erforderlich.

==== LG 1-5: Varianten von Entwicklungsvorgehen und deren "Beitrag" zu Architekturdokumentation kennen

* In eher formalen Entwicklungsvorhaben (etwa _safety-critical_) gelten eher hohe Ansprüche an Architekturdokumentation
* In eher leichtwichtigen Entwicklungsprozessen (agilen Prozessen) sollten Teams eine dem System und dessen Umfeld angemessene Art von Dokumentation wählen
* Je nach Vorgehen und Rahmenbedingungen des Vorhabens sind sehr unterschiedliche Dokumentationsarbeiten zu leisten.

**Comment by gernotstarke** [comment]
@StefanZoerner - hätte hierzu gerne Deine Meinung gehört, ob Du diese Art der "Transformation" ok findest oder eher nicht... es geht NICHT um das letzte Komma/Wording, sondern eher grundsätzlich...

Falls das für Dich ok wäre, würde ich mich an die anderen Kapitel setzen...

**Comment by StefanZoerner** [comment]
@gernotstarke - Mir gefällt die Struktur so sehr gut. Auch die Granularität, die Du für die Lernziele ausgewählt hast. Und hier speziell auch die Themen der Lernziele selbst.

Das erste Kapitel des Lehrplans ist fürchte ich etwas speziell, da es eher einleitend ist und Grundlage schafft. Trotzdem könnte ich mir vorstellen, die Lernziele mitunter mit aussagekräftigeren Verben zu versehen als "kennen". oder "verstehen". Das "abgrenzen" in LG 1-3 finde ich z.B. super.

Beispiel:
Nutzen und Ziele von Architekturdokumentation verstehen
Idee:
Den Teilnehmern sind Nutzen und Ziele von Architekturdokumentation bewußt.

Das finde ich aber für spätere Kapitel relevanter (statt "können" etwas aussagekräftigeres nahmen).

Wäre auch zu überlegen, ob man die klassische Form mit "Den Teilnehmern ..." oder den "Lernenden ..." am Anfang wählt. Finde ich etwas sperrig mitunter. Siehe z.B.
https://tu-dresden.de/mz/ressourcen/dateien/services/e_learning/didaktische-handreichung-formulierung-von-lernzielen-aus-dem-projekt-seco?lang=de

**Comment by gernotstarke** [comment]
danke Dir - der Hinweis auf das Paper war super... auf die Idee, mal bei den DidaktikerInnen nachzulesen war ich noch nicht gekommen.

Ich mache dann einfach (mit mittlerer Prio) mal weiter...
