### ISSUE TITLE
remove [[[bachmann,Bachmann 2000]]] reference: I doubt that anybody nowadays has this book?

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-adoc#30]
add modern books about communication instead, e.g. Communication Patterns
by [Jacqui Read] Released October 2023

add canvas-reference(s), e.g. ddd-canvas, architecture-communication-canvas

**Comment by StefanZoerner** [comment]
In fact, this is not a book but a Special Report (SR, 46 pages) of the CMU from the year 2000, which is freely available as a PDF. However, the contents are more than well covered by [Bass 2021] and [Clements+2010] and the SEI/CMU is already well represented in the references of the curriculum by the two books. In my view, we can therefore delete the reference.

**Comment by programming-wolf** [comment]
I added a new issue for the canvas stuff, see #35

**Comment by programming-wolf** [comment]
Removed with #33
